FEATURE: rand password

diff --git a/src/bash_functions b/src/bash_functions
--- a/src/bash_functions
+++ b/src/bash_functions
@@ -2085,26 +2085,31 @@ sfje() {
 }
 
 # hcons: "hydra scons"
-hcons() {
+hcons () 
+{ 
     local HELP=0
     local CLEAN=0
-    for arg in "$@"
-    do
+    for arg in "$@"; do
         if [ "$arg" == "--help" ]; then
             HELP=1
         elif [ "$arg" == "-c" ]; then
             CLEAN=1
         fi
     done
+
     if [ $CLEAN -eq 1 ]; then
         scons -c
     else
-        python hcons.py "$@"
-        if [ $HELP -eq 0 ]; then
+        python3 hcons.py "$@"
+        if [ $HELP -eq 0 ] && [ $? -eq 0 ]; then
             scons
+        elif [ $HELP -eq 0 ]; then
+            echo "Invalid hydra config...skipping scons"
+            return 1
         fi
     fi
 }
+
 # vrb: "vanilla rebase"
 vrb() {
     local start=${1:-"HEAD"}
