FEATURE: cdh much more usable now

diff --git a/src/bash_functions b/src/bash_functions
--- a/src/bash_functions
+++ b/src/bash_functions
@@ -1198,9 +1198,9 @@ gsync() {
 }
 
 # cdh: cd $HOME/$1
-cdh() {
-    cd $HOME/$1
-}
+# cdh() {
+#     cd $HOME/$1
+# }
 
 # ufw_monitor: run ufw_monitor.py
 ufw_monitor() {
@@ -1565,14 +1565,45 @@ epy() {
 }
 
 cd() {
-    builtin cd "$@" && echo $(pwd) >>~/.cd_history
-    local history=$(cat ~/.cd_history | tail -n 100)
-    echo "$history" >~/.cd_history
+    builtin cd "$@" && curr_dir=$(pwd | sed 's|/|\\/|g')
+    if grep -qx "$curr_dir" ~/.cd_history; then
+        sed -i "/^$curr_dir$/d" ~/.cd_history
+    fi
+    echo $(pwd) >>~/.cd_history
 }
 
 cdh() {
     local num_see=${1:-10}
-    cat ~/.cd_history | tail -n $num_see
+    iter=1
+    history=$(tac ~/.cd_history | head -n $num_see)
+    num_see=$(echo $history | wc -l)
+    echo "$history" | while read -r line; do
+        iter_str="$iter"
+        num_spaces=$((4 - ${#iter_str}))
+        spaces=$(printf "%${num_spaces}s")
+        echo "$iter$spaces$line"
+        ((iter++))
+    done
+    
+    # ask user input on which of these directories you'd like to go
+    while true; do
+        read -p "Where to? [1,$num_see] (q to quit): " -r REPLY
+
+        if [[ $REPLY == "q" ]]; then
+            break
+        fi
+
+        if [[ $REPLY =~ ^[0-9]+$ ]] && [[ $REPLY -ge 1 ]] && [[ $REPLY -le $num_see ]]; then
+            valid_input=1
+            local line=$(echo $history | head -n $REPLY | tail -n 1)
+            echo ""
+            echo "cd $line"
+            cd $line
+            break
+        else
+            echo "Invalid input. Please enter an integer between 1 and $num_see."
+        fi
+    done
 }
 
 pywest() {
@@ -1993,6 +2024,11 @@ cdje(){
 
 # mkje: "make julia env"
 mkje(){
+    # If $1 is empty, then we simply exit since this is unsafe
+    if [ -z "$1" ]; then
+        echo "Error: Environment name not provided."
+        return 1
+    fi
     # check if env already exists
     if [ -d "$HOME/.julia/environments/$1" ]; then
         echo "Environment already exists...would you like to delete and start fresh?"
@@ -2007,6 +2043,18 @@ mkje(){
     mkdir -p $HOME/.julia/environments/$1
 }
 
+# lsje: "list julia env"
+lsje(){
+    ls $HOME/.julia/environments
+}
+
+# sfje: "start fresh julia env"
+sfje(){
+    mkje $1
+    if [ $? -eq 0 ]; then
+        jenv $1
+    fi
+}
 echo "ignore this" >/dev/null
 
 source ~/.platform/functions
